config/routes.rb
Rails.application.routes.draw do
  resources :questions

  # get '/questions', to: 'questions#index' # localhost/questions
  
  # get '/questions/new', to: 'questions#new' # localhost/questions/new

  # get '/questions/:id/edit', to: 'questions#edit' # localhost/questions/new

  # post '/questions', to: 'questions#create' # localhost/questions
  
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
    validates :title, presence: true, length: {minimum:(2)}
    validates :body, presence: true, length: {minimum:(2)}

    def formatted_created_at
        created_at.strftime("%Y-%m-%d")
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index 
  	@questions = Question.all
  end

  def new 
    @question = Question.new 
  end

  def create 
    @question = Question.new question_params

    if @question.save 
      redirect_to questions_path
    else
      render :new
    end
  end

  def edit
    @question = Question.find_by id: params[:id]
  end

  def update
    @question = Question.find_by id: params[:id]

    if @question.update question_params
      redirect_to questions_path
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find_by(id: params[:id])
    @question.destroy
    redirect_to questions_path
  end

  def show
    @question = Question.find_by(id: params[:id])
  end


  private 

  def question_params
    params.require(:question).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class='container mx-auto py-4 w-full'>
      <ul class='flex align-center flex-col'>
        <li><%= link_to 'Home', root_path %></li> 
        <li><%= link_to 'Questions', questions_path %></li> 
      </ul>
    </nav>
    <main class='container mx-auto mt-10'>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Welcome to AskIt!</h1>

<p> &copy; Boboev <%= Time.now.year %></p>

app/views/questions/_form.html.erb
<%= form_with model: @question do |f| %>
  <div class="flex align-center justify-center flex-col gap-4">
    <div >
      <%= f.label :title %>
      <%= f.text_field :title, required: true, minlength: 2, placeholder: "Title" %>
    </div>

    <div>
      <%= f.label :body %>
      <%= f.text_area :body, required: true, minlength: 2, placeholder: "Body" %>
    </div>

  </div>
    <%= f.submit "Submit", disable_with: 'Submiting...' %>

<% end %>

app/views/questions/edit.html.erb
<h1 class="text-3xl">Edit question</h1>

<%= render "form" %>

app/views/questions/index.html.erb
<h1 class="text-3xl pb-4">Questions</h1>

<% @questions.each do |question| %>
  <h1 class="font-bold text-3xl py-5"><%= question.title %></h1>
  <time datetime="<%= question.formatted_created_at %>" >
    <%= question.formatted_created_at %>
  </time>
  <p><%= question.body %></p>
  <%= link_to "Show", question_path(question) %>
  <%= link_to "Edit", edit_question_path(question) %>
  <%= button_to "Destroy", question_path(question), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render "form" %>

app/views/questions/show.html.erb
<h1 class="text-3xl"><%= @question.title %></h1>

<p class="text-2xl">
  <time datetime="<%= @question.formatted_created_at %>" >
    <%= @question.formatted_created_at %>
  </time>

  <%= @question.body %>
</p>